name: Run Linting Checks
on: 
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --force
    - name: Run ESLint
      run: npm run lint
